name: CI

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
 
  deploy:
    environment: ludservilo
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Push to Dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_remote_url: 'ssh://dokku@ludservilo.astra137.dev:26903/7dfps'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
